### ISSUE TITLE
problem during installation on MacOS

### ISSUE THREAD

**Issue by sank96** [tushar-rishav/code2pdf#26]
Hi, 

I installed code2pdf with `pip install`
But when I try it on terminal occurs an error

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/code2pdf", line 11, in <module>
    load_entry_point('Code2pdf==1.0.0', 'console_scripts', 'code2pdf')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Code2pdf/__init__.py", line 1, in <module>
    from code2pdf import main
ModuleNotFoundError: No module named 'code2pdf'
```

**Comment by Chen-Cai-OSU** [comment]
I Tried both MacOS and Linux and had the same error.

**Comment by tushar-rishav** [comment]
@mett96 @Chen-Cai-OSU Please see https://github.com/tushar-rishav/code2pdf/issues/25#issuecomment-536477129

**Comment by tushar-rishav** [comment]
Closing in favor of https://github.com/tushar-rishav/code2pdf/issues/25
